version: '3.8'
services:
  fastapi:
    image: mhrimaz/aas-brain-concept-description-repo
    restart: unless-stopped
    environment:
      - DB_URI=redis://redis:6379
    depends_on:
      - redis
    ports:
      - "9192:80"
    expose:
      - 9192
    networks:
      - cd-repo-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.rule=Host(`cd.yourdomian.com`)"
      - "traefik.http.routers.app.tls.certresolver=myresolver"

  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    depends_on:
      - fastapi
    command:
      - "--api.insecure=false"
      - "--log.level=DEBUG"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    networks:
      - cd-repo-network
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
  redis:
    container_name:  redis
    image: redis:7.0-alpine
    restart: unless-stopped
    networks:
      - cd-repo-network
    ports:
      - "6019:6379"

  fuseki:
    container_name: fuseki
    command: ["--update" , "--mem", "/cd"]
    restart: unless-stopped
    image: fuseki
    ports:
      - "4030:3030"
    networks:
      - cd-repo-network

  graphexplorer:
    container_name: explorer
    image: graph-explorer
    restart: unless-stopped
    environment:
      - HOST=127.0.0.1
      - PROXY_SERVER_HTTPS_CONNECTION=false
      - GRAPH_EXP_HTTPS_CONNECTION=false
      - PUBLIC_OR_PROXY_ENDPOINT=http://127.0.0.1:4030/cd
      - GRAPH_TYPE=sparql
    ports:
      - "3434:80"
    networks:
      - cd-repo-network


  graphdb:
    container_name: graphdb
    image: ontotext/graphdb:10.4.2
    restart: unless-stopped
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms1g
    networks:
      - cd-repo-network
    volumes:
      - graphdbvolume:/opt/graphdb/home
    ports:
      - "7200:7200"

networks:
  cd-repo-network:
    external: true

volumes:
  graphdbvolume: